### ISSUE TITLE
Support status of this repo?

### ISSUE THREAD

**Issue by bw-yuhogg** [pmd/pmd-emacs#1]
My apologies if this sounds rude, but is this repo still supported?

I am considering including it in Homebrew-Emacs (see https://github.com/Homebrew/homebrew-emacs/issues/157) and knowing whether you intend to continue actively maintaining pmd-emacs would help clarify if we should package it.

Thanks!

**Comment by adangel** [comment]
Yes, this repo is still supported :)
Let me know if you find any problems and/or want to have anything changed - I'll be more than happy to support you.
Btw - the reason why this repo doesn't have much changes is, because PMD is called via the commandline - which means, you'll need to have PMD installed before you can use this emacs extension. As long as the CLI of PMD doesn't change in an incompatible way, there is usually no need to adjust this.
Regards, Andreas
